sudo: required
language: node_js
dist: trusty
node_js:
  - "8"

branches:
  only:
    - master

os:
  - linux
  #- osx ## OSX build is broken so suspend it for now.

cache:
  directories:
    - node_modules
    - $HOME/.electron

env:
  - SENCHA_VER=6.5.3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - rpm

install:
  - git config --global core.autocrlf input
  - git reset --hard HEAD
  - npm run sencha:clean
  - npm install
  - npm uninstall electron-prebuilt
  - npm i electron@$ELECTRON
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      curl -o sencha.sh.zip http://cdn.sencha.com/cmd/${SENCHA_VER}/no-jre/SenchaCmd-${SENCHA_VER}-linux-amd64.sh.zip;
    else
      curl -o sencha.sh.zip http://cdn.sencha.com/cmd/${SENCHA_VER}/no-jre/SenchaCmd-${SENCHA_VER}-osx-no_jre.app.zip;
    fi
  - unzip -p sencha.sh.zip > sencha-install.run
  - chmod +x sencha-install.run
  - ./sencha-install.run -q -Dall=true
  - cp env-sample.js env.js
before_script:
  - export PATH=~/bin/Sencha/Cmd/${SENCHA_VER}:${PATH}

script:
  - echo $TRAVIS_OS_NAME
  - node --version
  - npm --version
  - sencha audit
  - npm run sencha:compile
  - npm run build:$TRAVIS_OS_NAME

deploy:
  provider: releases
  api_key:
    secure: bYto8VS+zEFqKRjgBga69DgbjVPtHi4vRM+EGsNURe1b4ILRlwS8lJb5RbM+8w2UEPr8P9l959dC1pKYKjlJqEHwvDdTLFsDESO5uEUOtoEWUOnsNEwvvoNY1tFfPoFr1qhWjPWh4UGZzf/sfgXvSdoEg8cbmgbjkbEgGpKPri6Gigvosu/HT1ZCXVoud32uJ2ydfoWMfERXeQYk8u9x52Qx3XS7OMmUR1BvqifaSMt6K5oPFS1lOAXkxyCu1Sczg119+6MEWixImFcXYmPaAoHqLfPNICnhG3egiddq24f1ZGsGmfHgpliM4MNl74t99kPX6lcoQchTlhz4lVVI0lpHBymZwhIf4JjLSuZt81zW5cvJmu0CT22o/thnRFTY1MkaBDmdweaPtdYiMmAJuhwSQEeP6Mt4lqQNgtsNsBqkT6+n4T2l5RHagc/iC4TC58/4QZErKcVkaZnjy78trrQCKD9E1wLpm5hV84fF0FJLrEIhNYcSAJ6u1OJa2CaJ3u5OXFIuu01E+6CWu64pXgpIjkCRQU/JPSQVxdmwWqx4o4948NddBEx7Z3EsPkKU+5ccQr6dz7qESa8xnuERILclWO/LvdauYLhxtMVD2/fc/aKeP+6QxvNBClZT/eeO7bJDdCx/uWzm3Qo4k5+nyTl9bPUKLDzb5MuMh2x7flc=
  file_glob: true
  file:
    - "dist/*.deb"
    - "dist/*.tar.gz"
    - "dist/*.AppImage"
    - "dist/*.rpm"
    - "dist/mac/*.zip"
    - "dist/mac/*.dmg"
  skip_cleanup: true
  overwrite: true
  prerelease: true
  on:
    repo: TheGoddessInari/rambox
    tags: true
    all_branches: true

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a6584eccd211f35ecab6
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
